### PR TITLE
Updated and deleted URLs

### PR DESCRIPTION
**Pull request by jbohrer**
Two broken links removed, and one link updated to new location.

### CODE REVIEW

**Comment by jbohrer** [comment]
@cadecairos would you review and publish asap? One of the links was hijacked by a shady dating site. thanks.

**Comment by cadecairos** [comment]
Im on the move right now, but I'll merge and deploy asap

**Review by cadecairos — APPROVED** [review]

**Comment by cadecairos** [comment]
this has been deployed, and I've invalidated the CDN to clear out cached pages.

**Comment by jbohrer** [comment]
Thank you, all looks good!

**Pull request merged**
